export const products = [
    {
        id: 1,
        name: "Suitcase",
        description:  "Rigid luggage for business trips, weekend getaways or as international carry-on baggage.",
        price: 75.59,
        colors: ["yellow"],
        sizes: [""],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682814364/imagenes%20henry/maleta_de_viaje_Henry_juye8n.png",
        category: "Bookshop",
        stock: 8
         
      },
      {
        id: 2,
        name: "T-shirt",
        description:  "T-shirt Smooth Cotton Jersey Combed Premium.",
        price: 16.99,
        colors: ["white", "grey", "yellow","black"],
        sizes: ["XS","S", "M", "L","XL","XXL"],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682800364/imagenes%20henry/remera_manga_larga0_ynqelb.png",
        category: "Dress",
        stock: 47
      },
      {
        id: 3,
        name: "Diver",
        description:  "Diver Smooth Cotton Jersey Combed Premium.",
        price: 26.62,
        colors: ["black","grey", "white", "yellow"],
        sizes: ["XS","S", "M", "L","XL","XXL"],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682800363/imagenes%20henry/buzo_blanco0_sjhbmz.png",
        category: "Dress",
        stock: 88
      },
      {
        id: 4,
        name: "Rigid suitcase",
        description:  "Rigid rotating luggage for business trips, weekend getaways or as international carry-on baggage.",
        price: 119.99,
        colors: ["black", "white", "yellow"],
        sizes: [""],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682800364/imagenes%20henry/maletadeviaje0_ha2i4z.png",
        category: "Bookshop",
        stock: 77
      },
      {
        id: 5,
        name: "Cap",
        description:  "Plain cap with Henry stag.",
        price: 9.52,
        colors: ["white", "yellow", "black"],
        sizes: ["S","M","L"],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682800363/imagenes%20henry/gorra_blanca0_agodsi.png",
        category: "Dress",
        stock: 25
      },
      {
        id: 6,
        name: "Piluso",
        description:  "Smooth piluso with Henry styling.",
        price: 19.60,
        colors: ["black", "yellow", "white"],
        sizes:  ["S"],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682875784/imagenes%20henry/Piluso_negro_-_Henry_azfv2j.jpg",
        category: "Dress",
        stock: 23
      },
      {
        id: 7,
        name: "Jacket",
        description:  "Jacket Smooth Cotton Jersey Combed Premium.",
        price: 60.33,
        colors: ["black", "white"],
        sizes: ["XS","S", "M", "L","XL","XXL"],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682875803/imagenes%20henry/Campera_chorizera_negra_-_Henry_klgsdd.jpg",
        category: "Dress",
        stock: 45
      },
      {
        id: 8,
        name: "Pants",
        description:  "Long plain pants with Henry stag.",
        price: 23.59,
        colors: ["black", "white", "yellow"],
        sizes: ["S", "M", "L","XL","XXL","XS"],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682814588/imagenes%20henry/Pantalon_largo_blanco_-_Henry_nqlrdz.jpg",
        category: "Dress",
        stock:  32
      },
      {
        id: 9,
        name: "Shorts",
        description:  "Plain shorts with Henry stag.",
        price: 9.80,
        colors: ["yellow", "black", "white"],
        sizes: ["XS","S", "M", "L","XL","XXL"],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682814588/imagenes%20henry/Pantalon_corto_negro_-_Henry_d3b0c9.jpg",
        category: "Dress",
        stock:  13
      },
      {
        id: 10,
        name: "Ultra diver",
        description:  "Diver ultra Smooth Cotton Jersey Combed Premium.",
        price: 38.22,
        colors: ["black", "white"],
        sizes: ["XS","S","M","L","XL","XXL"],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682814587/imagenes%20henry/Buzo_negro_-_Henry_ruophm.jpg",
        category: "Dress",
        stock: 55
      },
      {
        id: 11,
        name: "Jacket woman",
        description:  "White jacket woman with Henry print.",
        price: 22.72,
        colors: ["white", "black"],
        sizes: ["XS","S", "M", "L","XL","XXL"],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682800364/imagenes%20henry/buzo_mujer0_gefrb6.png",
        category: "Dress",
        stock: 35
      },
      {
        id: 12,
        name: "Gloves",
        description:  "Gloves for the cold with Henry stag.",
        price: 5.99,
        colors: ["black", "white", "yellow"],
        sizes: ["S", "M", "L","XL"],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682814588/imagenes%20henry/Guantes_negros_-_Henry_spcmie.jpg",
        category: "Dress",
        stock: 14
      },
      {
        id: 13,
        name: "Mesh",
        description:  "Smooth mesh with a Henry stag.",
        price: 18.00,
        colors: ["white", "black", "yellow"],
        sizes: ["XS","S", "M", "L","XL","XXL"],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682876905/imagenes%20henry/Malla_amarillo_-_Henry_gbjjhv.jpg",
        category: "Dress",
        stock: 10
      },
      {
        id: 14,
        name: "Hat",
        description:  "Cap for the smooth cold with a standard of Henry.",
        price: 14.07,
        colors: ["black", "white", "yellow"],
        sizes:  ["S"],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682814588/imagenes%20henry/Gorrito_negro_-_Henry_c4hngd.jpg",
        category: "Dress",
        stock: 58
      },
      {
        id: 15,
        name: "Sneakers",
        description:  "Urban sneakers with unisex Henry logo.",
        price: 53.55,
        colors: ["white", "black"],
        sizes: ["36","37","38","39","40","41","42","43"],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682814588/imagenes%20henry/Zapatillas_urbanas_negras_-_Henry_avfali.jpg",
        category: "Dress",
        stock: 29
      },
      {
        id: 16,
        name: "Bag",
        description:  "Large smooth space bag with Henry styling.",
        price: 65.00,
        colors: ["yellow", "white"],
        sizes: [""],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682814587/imagenes%20henry/Bolso_blanco_-_Henry_ra9eqt.jpg",
        category: "Dress",
        stock: 19
      },
      {
        id: 17,
        name: "Knapsack",
        description:  "Plain basic backpack with Henry's logo.",
        price: 18.92,
        colors: ["black", "yellow"],
        sizes: [""],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682877062/imagenes%20henry/Morral_negro_-_Henry_lr8iql.jpg",
        category: "Bookshop",
        stock: 32
      },
      {
        id: 18,
        name: "Tennis cap",
        description:  "Tennis style cap with Henry's logo.",
        price: 20.00,
        colors: ["yellow", "white", "black"],
        sizes: ["S","M","L"],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682814588/imagenes%20henry/Gorra_tenis_negra_-_Henry_vieopf.jpg",
        category: "Dress",
        stock: 13
      },
      {
        id: 19,
        name: "Holster",
        description:  "Cartridge case for tools with the Henry logo.",
        price: 9.99,
        colors: ["blue","yellow","white"],
        sizes: [],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682875724/imagenes%20henry/Cartuchera_azul_-_Henry_kfn5rr.jpg",
        category: "Bookshop",
        stock: 63
      },
      {
        id: 20,
        name: "Stapler",
        description:  "Stapler with Henry's logo.",
        price: 6.22,
        colors: ["red", "black","blue"],
        sizes: [""],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682814424/imagenes%20henry/Engrapador_azul_-_Henry_ql8fpq.jpg",
        category: "Bookshop",
        stock: 36
      },
      {
        id: 21,
        name: "Trash can",
        description:  "Trash can with Henry's logo.",
        price: 12.75,
        colors: ["red", "blue", "black"],
        sizes: [""],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682877234/imagenes%20henry/Cesto_azul_-_Henry_cpmrrh.jpg",
        category: "Home",
        stock: 41
      },
      {
        id: 22,
        name: "Thermos",
        description:  "Stainless steel thermos retains temperature for more than a full day.",
        price: 29.99,
        colors: ["white", "black"],
        sizes: [""],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682814364/imagenes%20henry/Termo_blanco_Henry_kfldxr.png",
        category: "Home",
        stock: 23
      },
      {
        id: 23,
        name: "Mate",
        description:  "Thermal matte with Henry's logo.",
        price: 20.00,
        colors: ["yellow", "white"],
        sizes: [""],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682815666/imagenes%20henry/Mate_termico_-_Henry_gchq0a.jpg",
        category: "Home",
        stock: 28
      },
      {
        id: 24,
        name: "Cell phone holder",
        description:  "Cell phone holder with Henry's logo.",
        price: 8.97,
        colors: ["black", "white"],
        sizes: [""],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682815663/imagenes%20henry/Porta_celular_-_Henry_bperih.jpg",
        category: "Technology",
        stock: 18
      },
      {
        id: 25,
        name: "Notebook case",
        description:  "Notebook case with high protection.",
        price: 15.98,
        colors: ["black", "white"],
        sizes: [""],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682814487/imagenes%20henry/Bolso_Notebook_N_Henry_Blanco_txikb3.jpg",
        category: "Technology",
        stock: 34
      },
      {
        id: 26,
        name: "Mouse",
        description:  "High quality computer mouse with Henry logo.",
        price: 26.59,
        colors: ["yellow", "white", "black"],
        sizes: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682800364/imagenes%20henry/mouse-inalambrico0_med6pw.png",
        image: " /mouse.jpg",
        category: "Technology",
        stock: 29
      },
      {
        id: 27,
        name: "Keyboard",
        description:  "Computer keyboard with henry's logo.",
        price: 37.99,
        colors: ["black"],
        sizes: [""],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682814488/imagenes%20henry/Teclado_A_y_N_Henry_Blanco_t8slql.jpg",
        category: "Technology",
        stock: 20 
      },
      {
        id: 28,
        name: "Pendrive",
        description:  "Henry pendrive with capacity of 64/128 GB.",
        price: 12.41,
        colors: ["yellow", "black", "white"],
        sizes: [""],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682815360/imagenes%20henry/Pendrive_Am_Logo_w78wcq.jpg",
        category: "Technology",
        stock: 7
      },
      {
        id: 29,
        name: "Earphones",
        description:  "High quality headphones with Henry's logo.",
        price: 39.99,
        colors: ["white", "black", "yellow"],
        sizes: [""],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682814486/imagenes%20henry/Auri_A_Logo_gvkymz.jpg",
        category: "Technology",
        stock: 32
      },
      {
        id: 30,
        name: "Wireless headphones",
        description: "Best quality high-end wireless headphones and technology.",
        price: 49.95,
        colors: ["black", "yellow", "white"],
        sizes: [""],
        image: "https://res.cloudinary.com/dyeknjnsi/image/upload/v1682814487/imagenes%20henry/Auriculares_Negros_keda2v.jpg",
        category: "Technology",
        stock: 16
      },
]